webtalk_init -webtalk_dir C:/Users/james/OneDrive/Dokumente/Vivado/SoC_Projects/unipolar_stepper_motor/unipolar_stepper_motor.sim/sim_1/behav/xsim/xsim.dir/steppermotor_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar  2 17:06:30 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "10b3117d-0ccb-486e-b89e-c6efef2271ff" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2e0c2bec2f8b4001873a27597b9a0d4d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "84" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7728_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1916798892 -regid "" -xml C:/Users/james/OneDrive/Dokumente/Vivado/SoC_Projects/unipolar_stepper_motor/unipolar_stepper_motor.sim/sim_1/behav/xsim/xsim.dir/steppermotor_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/james/OneDrive/Dokumente/Vivado/SoC_Projects/unipolar_stepper_motor/unipolar_stepper_motor.sim/sim_1/behav/xsim/xsim.dir/steppermotor_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/james/OneDrive/Dokumente/Vivado/SoC_Projects/unipolar_stepper_motor/unipolar_stepper_motor.sim/sim_1/behav/xsim/xsim.dir/steppermotor_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
